services:
  booking-backend:
    image: rhzarzky/booking-backend:dev
    container_name: booking-backend
    env_file:
      - .env.backend
    build: 
      context: ./backend
    volumes:
      - /root/booking-backend/storage/app/public:/app/storage/app/public
      - /root/booking-backend/public:/app/public
    ports:
      - "8080:8080"
    networks:
      - booking-network
      - postgres-network
    #   - mysql-network
    #   - nginx-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/up"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  booking-frontend:
    image: rhzarzky/booking-frontend:dev
    container_name: booking-frontend
    env_file:
      - .env.frontend
    build: 
      context: ./vue-admin
    ports:
      - "8081:80"
    networks:
      - booking-network
    #   - nginx-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  client-frontend:
      image: rhzarzky/client-frontend:dev
      container_name: client-frontend
      env_file:
        - .env.frontend
      build:
        context: ./vue
      ports:
        - "8082:80"
      networks:
        - booking-network
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 5s

networks:
  booking-network:
    name: booking-network
    driver: bridge
  postgres-network:
    name: postgres-network
    external: true

#   mysql-network:
#     name: mysql-network
#     external: true

#   nginx-network:
#     name: nginx-network
#     external: true