org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17

kotlin.code.style=official
kotlin.version=2.1.20